- package-lock.json
- package.json
- src/app.module.ts
- src/auth/auth.controller.ts
- src/auth/auth.module.ts
- src/controller/batches/batch.controller.ts
- src/controller/classes/classes.controller.ts
- src/controller/classes/classes.module.ts
- src/controller/classes/classes.service.ts
- src/controller/classes/dto/classes.dto.ts
Reverts navgurukul/zuvy-server#10
> Revert "Revert "Classes""

- package-lock.json
- package.json
- src/controller/batches/batch.controller.ts
- src/controller/batches/batch.service.ts
- src/controller/bootcamp/bootcamp.controller.ts
- src/controller/bootcamp/bootcamp.module.ts
- src/controller/bootcamp/bootcamp.service.ts
- src/middleware/jwt.middleware.ts
Besides pagination and searching students api,also modification in getBatchById to get the instructor name is done.
> Includes pagination in students,searching students by search query

- src/controller/submissions/submission.service.ts
Reverts navgurukul/zuvy-server#134
> Revert "add get  api assessmentStudentsInfoBy"

- drizzle/schema.ts
- src/controller/codingPlatform/codingPlatform.controller.ts
- src/controller/codingPlatform/codingPlatform.service.ts
Reverts navgurukul/zuvy-server#170
> Revert "modify the coding plarform schema and GET, POST, RB APi's,"

- drizzle/schema.ts
- src/controller/content/content.controller.ts
- src/controller/content/content.service.ts
- src/controller/content/dto/content.dto.ts
Reverts navgurukul/zuvy-server#192
> Revert "Admin side Apis added pt-1"

- src/controller/adminAssessment/adminAssessment.service.ts
- src/controller/content/content.service.ts
- src/controller/progress/tracking.service.ts
- src/controller/submissions/submission.service.ts
Reverts navgurukul/zuvy-server#274
> Revert "Prod/content assessment"

- src/controller/content/content.controller.ts
- src/controller/content/content.service.ts
- src/controller/instructor/instructor.service.ts
1. Pagination has been added to both the Get All Quiz Questions and Get All Coding Questions.
2. Error handling has been implemented for the "Search Recording Class" feature on the instructor's side.
> Pagination has been added to both the quiz and coding questionn

- drizzle/schema.ts
- src/controller/content/content.service.ts
- src/controller/progress/tracking.service.ts
1. Added randomization on the student side.
2. On the admin side, selected MCQ questions are now appearing with variants.
> completed randomization in student side.

- src/controller/bootcamp/bootcamp.service.ts
- src/controller/content/content.controller.ts
- src/controller/content/content.service.ts
- src/controller/progress/tracking.service.ts
1. Add the duplicate course name validation in Bootcamp.
2. Add validation to ensure all questions are attempted before storing data in the quizTracing table. If the chosenOptions array length doesn't match the questions array length, an error message 'You must attempt all the questions' will be shown, and the data won't be saved. Once all questions are answered, the data will be stored successfully. 
3. Add the pagination in the getAllOpenEndedQuestions API.
> Duplicate Course Name Validation.

- src/controller/bootcamp/bootcamp.controller.ts
- src/controller/bootcamp/bootcamp.service.ts
- src/controller/bootcamp/dto/bootcamp.dto.ts
1. Update user name and mail Id by using userId.
> Update user details

- src/controller/content/content.service.ts
- src/controller/progress/tracking.service.ts
- src/controller/student/student.controller.ts
- src/controller/student/student.service.ts
1. Add functionality to delete multiple students with progress on the admin side.
2. Remove the automatic mark as done from the coding chapter.
3. Add functionality to not reorder the module if any students have started the module.
4. Add space between sentences for correct grammar.
> Add functionality to delete multiple students.

- src/controller/codingPlatform/codingPlatform.service.ts
- src/helpers/index.ts
Reverts navgurukul/zuvy-server#331
> Revert "Refactor template generation functions for improved clarity and efficiency"

- src/controller/codingPlatform/codingPlatform.service.ts
1) Changed the status code from 404 to 200.
> Changed the status code

- src/controller/content/content.service.ts
1. Add test case chapter details by ID API.
> Added test case in chapterDetailsById API

- src/controller/progress/tracking.service.ts
1. Added the chapter name in response to the assessment submission API.
> Added the chapter Name in response on get assessment submission api.

- src/controller/codingPlatform/codingPlatform.controller.ts
- src/controller/codingPlatform/codingPlatform.service.ts
Updated the logic to get rid of status issue in coding submission like in queue/in processing
> Updated the logic to get rid of status issue in coding submission

- src/controller/adminAssessment/adminAssessment.service.ts
- src/controller/content/content.controller.ts
- src/controller/content/content.service.ts
- Start assessment is called multiple times in UI for various data. Everytime its called,a new submission is created.
To prevent it, have discussed with Prashant and implemented a flag which will be true when clicked on enter full screen for first time.And for rest other time, it will be false and based on that we will make the entry
> Hot fix of start assessment api .

- src/controller/progress/tracking.module.ts
- src/controller/progress/tracking.service.ts
1) Added the state update on the student side.
> Added the state in student side.

- src/controller/student/student.service.ts
1. Sent the live session link in the upcoming events API.
> Sent the live session link in response.

- src/controller/student/student.service.ts
sending isLock status for modules in syllabus api for student side
> sending isLock status for modules in syllabus api for student side

- src/controller/student/student.controller.ts
- src/controller/student/student.service.ts
- src/controller/submissions/submission.controller.ts
- src/controller/submissions/submission.service.ts
2 new apis created for live sessions submissions and added from and to date filters in attendance for bootcamps
> 2 new apis created for live sessions submissions and added filters in attendance api
